# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title 
permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

# paginate: 7
# paginate_path: "posts.html/page:num"

production_url : http://dr3wh0.net

# RSS Feed
# https://github.com/snaptortoise/jekyll-rss-feeds
name: DR3WH0
description: Time Travel &amp; Other Anomalies
url: http://dr3wh0.net

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0
  BASE_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html  
  
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

# Prose.io Configuration
#
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://dr3wh0.net/'
#  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
#  media: 'media'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "DR3WH0"
              value: "dr3wh0"
            - name: "Poetry"
              value: "poetry"
            - name: "Programming"
              value: "programming"
            - name: "Prose"
              value: "prose"
            - name: "Radio"
              value: "radio"

lastfm:
  username: DR3WH0
  api: 838e67db61e754959ef27bd24aa5a1f8

tracks :
  - name : Aphex Twin - Avril 14th
    url : http://www.youtube.com/watch?v=MBFXJw7n-fU
  - name : Low - Fearless (P.Floyd Cover)
    url : http://www.youtube.com/watch?v=2LyEcWxI3UQ
  - name : Stars Of The Lid - December Hunting
    url : http://www.youtube.com/watch?v=u-MXZDkcPKM
  - name : Abfarhrt Hinwil - Radiowellen
    url : http://t.co/JrzTapEmhw
  - name : Com Truise - Cyanide Sisters 
    url : http://t.co/BRepBDsdAz
  - name : Point 7 - One Movie
    url : http://freedownloads.last.fm/download/209722767/One%2BMovie.mp3
  - name : Gimmik - Sister Moon
    url : http://goo.gl/MTuAeR
  - name : zotalayer - ebb telemetry
    url : http://t.co/aN2HsvUyAK
#  - name : Gimmik - Ernie & Bert
#    url : http://freedownloads.last.fm/download/798/Ernie%2B%2526%2BBert.mp3
  - name : Abfarht Hinwil - Bumperstufe2
    url : http://t.co/7ZG79jKjQs
  - name : Point 7 - Ous
    url : http://t.co/S3zq3Oyuy7
  - name : Gimmik - Back to Basics
    url : http://t.co/PuisfO2zhP
  - name : Sense - zed
    url : http://t.co/WM16WZ9ug6
  - name : Point 7 - Hacker IP
    url : http://t.co/YIjeAFdwzi
  - name : Abfahrt Hinwil - Links Oben 
    url : http://t.co/XUiKfWxTj6
  - name : Gimmik - Thing on a Spring
    url : http://t.co/hrwKRcv7e4
  - name : Abfahrt Hinwil - Sonic Surface 
    url : http://t.co/5PfdFmiKVg
  - name : Abfahrt Hinwil - Trilogy
    url : http://t.co/Wg6EBntsgS
  - name : Abfahrt Hinwil - Tech 8
    url : http://t.co/5vxj8bRhV9
  - name : Robert Schumann - Lotus Flower
    url : http://t.co/lXz85vA3er
  - name : ESEM - Thinmute
    url : http://t.co/Oft4EPe8lw
  - name : Abfahrt Hinwil - The Light
    url : http://t.co/mifR3LfBye
  - name : Johannes Brahms - Ballade in Dm
    url : http://t.co/dlt70d9sPn
  - name : Gimmik - Syntax
    url : http://t.co/MMYKQj4Lhq
  - name : Robert Schumann - Impromptu No.3
    url : http://t.co/AxFnDtXJPb
  - name : aAirial - Les minutes deviennent secondes..
    url : http://t.co/nt1zCg5Bhi
  - name : Motionfield - Timelines
    url : http://t.co/YCKXGIPIbc
  - name : Iqtu - Strategy 5
    url : http://t.co/rNBXiucwzi
  - name : Monoceros - Sinus
    url : http://t.co/L2CBxmzTUg
  - name : Praveen - Only to Make Ammends
    url : http://t.co/ag3Us8L3kL
  - name : Verbose - shram
    url : http://t.co/lkaM6frYOz
  - name : Sovacusa - Osloka
    url : http://t.co/UEN8ulgYtm
  - name : Monoceros - Background birds
    url : http://t.co/WbSQ4cMT9n
  - name : IJO - have a nice day
    url : http://t.co/RZ0hsqpWNy
  - name : Monoceros - Fractions (2.0)
    url : http://t.co/EW5qU4R6Me
  - name : aAirial - Smriti
    url : http://t.co/fSN4HguhH3
  - name : Yvat - Accession
    url : http://t.co/Mg0Gl2PujQ
  - name : IJO - Jamaica Road
    url : http://t.co/QgrDmcYdbp
  - name : IJO - Little Miss Summer
    url : http://t.co/PLe1VFiK7i
  - name : Monoceros - Pizzicato spoon
    url : http://t.co/8oIF88p9Ry
# not working in SCM 2013-09-07
#  - name : Verbose - Personaradar
#    url : http://t.co/5EYuuMc4Mh
  - name : Recue - Orchard Rd.
    url : http://t.co/ksELzRWoul
  - name : Veell - Qlocker
    url : http://t.co/CHmhrFiYhB
  - name : Proswell - Ahi
    url : http://goo.gl/zRwIqG
    date: 2013-09-06 Fri 04:49:55
  - name : Monoceros - Life In a Fishbowl (Are They* Watching Us?)
    url : http://goo.gl/9zdcRd
    date: 2013-09-06 Fri 05:10:00
  - name : Gas - Microscopic
    url : http://goo.gl/Jp4Tgf
    date: 2013-09-14 Sat 08:51:09
  - name : Natural Snow Buildings - Memories found in a bill from a small animal vet
    url : http://goo.gl/TOBxil
    date: 2013-09-14 Sat 10:28:44
  - name : Claude Debussy - Hommage a Rameau (Debussy)
    url : http://goo.gl/5DjDXb
    date: 2013-09-15 Sun 09:33:23
  - name : Marcos Paiva - Edison N. 2
    url : http://goo.gl/VtzUku
    date: 2013-09-16 Mon 03:42:23
  - name : Dum Dum Dum - 24689
    url : http://goo.gl/e4GqDZ
    date: 2013-09-16 Mon 03:45:37
  - name : G.M.Orchestra - Erotic Club (Live)
    url : http://goo.gl/iov5uT
    date: 2013-09-16 Mon 03:48:51
  - name : Sax a. Moryson - Rhythm Of My Hearts (Live)
    url : http://goo.gl/JiwPtL
    date: 2013-09-16 Mon 04:30:25
  - name : pumpkin jacket - The perils of yeast
    url : http://goo.gl/pf7IP7
    date: 2013-09-16 Mon 05:35:22
  - name : Mahat - Relief
    url : http://goo.gl/wMcQ8S
    date: 2013-09-16 Mon 16:30:33
  - name : Eric Romine - Cosmic Dust
    url : http://goo.gl/W6T0DL
    date: 2013-09-17 Tue 04:32:43
  - name : Fieldtriqp - Old Haunts
    url : http://goo.gl/A1VvQS
    date: 2013-09-19 Thu 04:27:24
  - name : Fieldtriqp - windswept
    url : http://goo.gl/25TXmG
    date: 2013-09-19 Thu 05:39:44
  - name : Gimmik - Square Two
    url : http://goo.gl/YuuPgd
    date: 2013-09-19 Thu 17:08:49
  - name : Abfahrt Hinwil - Syntax Data
    url : http://goo.gl/0biu9W
    date: 2013-09-19 Thu 17:28:05
  - name : Kettel - Not Gonna Get
    url : http://goo.gl/XjDkoi
    date: 2013-09-19 Thu 17:55:26
# find out which character breaks the JS
#  - name : Gimmik - Qoui Donc M'importe, Godot?!
#    url : http://goo.gl/kb9tJK
#    date: 2013-09-23 Mon 03:38:24
  - name : Lackluster - Starcell U.K.
    url : http://goo.gl/d4uaNn
    date: 2013-09-23 Mon 03:51:03
  - name : Monoceros - How was the earth? (mother)
    url : http://goo.gl/BgtCtk
    date: 2013-09-24 Tue 03:31:44
  - name : Praveen - Float
    url : http://goo.gl/LyWAi2
    date: 2013-09-24 Tue 03:38:00
  - name : aAirial - On the eve of summer
    url : http://goo.gl/Xtrh19
    date: 2013-09-24 Tue 03:42:14
  - name : Sinq - Acid Jazz
    url : http://goo.gl/8K9RVy
    date: 2013-09-24 Tue 04:25:25
  - name : Robert Schumann - Impromptu #3 (Schumann)
    url : http://goo.gl/dbOCRA
    date: 2013-09-27 Fri 17:18:41
  - name : Lithops - Attached
    url : http://goo.gl/OSgb47
    date: 2013-09-28 Sat 11:51:09
  - name : Oval - Ah!
    url : http://goo.gl/T253wb
    date: 2013-09-28 Sat 13:06:41
  - name : ESEM - Caffeine
    url : http://goo.gl/Z5MIT5
    date: 2013-10-01 Tue 06:42:53
  - name : Monoceros - Capvespre
    url : http://goo.gl/N6zSto
    date: 2013-10-02 Wed 20:43:32
  - name : Point 7 - Space Formula
    url : http://goo.gl/VzyQE7
    date: 2013-10-03 Thu 05:01:39
  - name : Proswell - Yuko Pailey
    url : http://goo.gl/gHixJw
    date: 2013-10-03 Thu 05:14:18
  - name : Monoceros - happiness
    url : http://goo.gl/IY9vwO
    date: 2013-10-03 Thu 05:24:58
  - name : Abfahrt Hinwil - Radiowellen
    url : http://goo.gl/FQMnlk
    date: 2013-10-04 Fri 05:05:13
  - name : Kettel - Twinkle Twinkle That Is You
    url : http://goo.gl/dlBJpx
    date: 2013-10-04 Fri 06:36:28
  - name : Gimmik - Floating Clear
    url : http://goo.gl/ndn42a
    date: 2013-10-05 Sat 12:28:17
