# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

# paginate: 7
# paginate_path: "posts.html/page:num"

production_url : http://DR3WH0.github.io

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0
  BASE_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html  
  
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

# Prose.io Configuration
#
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://DR3WH0.github.io/'
#  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
#  media: 'media'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Category"
          value: "DR3WH0"

tracks :
  - name : Aphex Twin - Avril 14th
    url : http://www.youtube.com/watch?v=MBFXJw7n-fU
  - name : Low - Fearless (P.Floyd Cover)
    url : http://www.youtube.com/watch?v=2LyEcWxI3UQ
  - name : Stars Of The Lid - December Hunting
    url : http://www.youtube.com/watch?v=u-MXZDkcPKM
  - name : Abfarhrt Hinwil - Radiowellen
    url : http://t.co/JrzTapEmhw
  - name : Com Truise - Cyanide Sisters 
    url : http://t.co/BRepBDsdAz
  - name : Point 7 - One Movie
    url : http://freedownloads.last.fm/download/209722767/One%2BMovie.mp3
  - name : Gimmik - Sister Moon
    url : http://goo.gl/MTuAeR
  - name : zotalayer - ebb telemetry
    url : http://t.co/aN2HsvUyAK
#  - name : Gimmik - Ernie & Bert
#    url : http://freedownloads.last.fm/download/798/Ernie%2B%2526%2BBert.mp3
  - name : Abfarht Hinwil - Bumperstufe2
    url : http://t.co/7ZG79jKjQs
  - name : Point 7 - Ous
    url : http://t.co/S3zq3Oyuy7
  - name : Gimmik - Back to Basics
    url : http://t.co/PuisfO2zhP
  - name : Sense - zed
    url : http://t.co/WM16WZ9ug6
  - name : Point 7 - Hacker IP
    url : http://t.co/YIjeAFdwzi
  - name : Abfahrt Hinwil - Links Oben 
    url : http://t.co/XUiKfWxTj6
  - name : Gimmik - Thing on a Spring
    url : http://t.co/hrwKRcv7e4


